### ISSUE TITLE
Bookmarks for guide

### ISSUE THREAD

**Issue by HarshdipD** [UWindsorCSS/hub#105]
We should have bookmarks for each section of the guide page. This would be easier to find a section directly from the URL.
Example: https://css.uwindsor.ca/guide#courses

**Comment by EricPickup** [comment]
We have bookmarks for the main headings (as you can see in the table of contents and similar to the one you linked) but I think it would be great to have bookmarks for the subsections/subheadings as well, if that's what you mean. Feel free to take that up if you have time @HarshdipD

**Comment by EricPickup** [comment]
Closed by #114
