### ISSUE TITLE
Create internship job board in CSS site

### ISSUE THREAD

**Issue by EricPickup** [UWindsorCSS/hub#117]
Users have requested that we add tools to the CSS site. This would be a first and a huge one.

There are plenty of job boards out there for US internships. I'd like to create one for Canadian positions.

Some features I'd like to add:

- [x] Admins can add/remove/review postings

- [x] Users can submit postings for review

- [x] Users can report a posting/link as stale or outdated

- [x] Admins can see and approve reports or new submissions

- [ ] Bot will automatically send new postings into the #internships channel in Discord

Pages needed:

- [x] New posting page (gets posted by admins, gets submitted for approval by users)

- [x] Edit posting page (admin only)

- [x] Review page for admins (review reports or new postings)

- [x] Job listings

**Comment by amanpatel123** [comment]
This sounds interesting, I would love to work on this. Eric do you want to assign a few tasks to me out of these?

**Comment by Scetch** [comment]
Should make the postings become stale and need reapproval after X amount of time so old ones that never get checked don't sit on the site for too long.

**Comment by HarshdipD** [comment]
What's the in-progress status of this issue? I thought this was completed

**Comment by EricPickup** [comment]
I've updated the check-list, last thing I can think of right now is the Discord messages
