### ISSUE TITLE
Copy registrant emails to clipboard

### ISSUE THREAD

**Issue by EricPickup** [UWindsorCSS/hub#122]
With an event that has registrations enabled, admins can see the guest list of students who've signed up for the event.
![image](https://user-images.githubusercontent.com/1490434/72669276-ae2e4b00-39fd-11ea-8225-be8e2dc46287.png)

We like to send reminder emails or updates to the people who signed up. It'd be great to be able to click one button that would copy the text list of email addresses of students who've signed up to the clipboard so that I can paste it in my gmail "Send to" box. 

Something like this:
![image](https://user-images.githubusercontent.com/1490434/72669292-e2a20700-39fd-11ea-81fa-8a4b911ce014.png)

The string that would by copied to the clipboard would be emails separated by commas, e.g.
`pickup@uwindsor.ca, lucie115@uwindsor.ca, wilson3l@uwindsor.ca`.

Important things to note:
- This button should only be available for admins (like the guest list already is)
- I'm guessing this would have to be done with javascript - it's important that the client side code does not expose the list of emails to non-admins

**Comment by EricPickup** [comment]
@amanpatel123 or @HarshdipD you guys might be interested in this?

**Comment by amanpatel123** [comment]
@EricPickup this looks interesting. I will definitely look at it today

**Comment by HarshdipD** [comment]
Looks like a fun feature. @amanpatel123  let me know your progress on this and I can continue on Monday if it's still not complete

**Comment by HarshdipD** [comment]
@EricPickup  would you not prefer this to be done by rails instead? Like you can get emails of all registered users and use the mailer. Would be easier than using js which will only copy the emails.

**Comment by EricPickup** [comment]
I'd prefer to just copy to clipboard since we'd need to provide an interface to send emails using the mailer.

**Comment by EricPickup** [comment]
Not sure if either of you are still interested @HarshdipD @amanpatel123, but I made a change that added the list of emails in a string to the event page for admins in this change: https://github.com/UWindsorCSS/hub/commit/6dd6fcc2a560316fd9954c5f9e518212a67788da.

Looks like this:
![image](https://user-images.githubusercontent.com/1490434/76714066-6f65fa00-66fb-11ea-881d-a974ce2b173e.png)

Now it should be pretty straight forward to create a button that uses javascript to copy the content of that block of text to the clipboard.

**Comment by amanpatel123** [comment]
@EricPickup sounds good! Will look into it today
