### ISSUE TITLE
Implement pagination for events list

### ISSUE THREAD

**Issue by EricPickup** [UWindsorCSS/hub#135]
Right now past events only shows the last two. It'd be cool if you could browse past events through pagination

**Comment by HarshdipD** [comment]
I can work on this. How about we use tabs instead of the long page scroll? These tabs for upcoming/past events can have pagination within them
https://getbootstrap.com/docs/4.0/components/navs/#tabs
@EricPickup

**Comment by EricPickup** [comment]
@HarshdipD If you mean tabs for upcoming events vs past events, i think that's a good idea
