### ISSUE TITLE
Upgrade ruby

### ISSUE THREAD

**Issue by EricPickup** [UWindsorCSS/hub#140]
We're currently on 2.4.2, however 2.7.0 came out late last year and is the latest release. Should upgrade to that.

**Comment by amanpatel123** [comment]
@EricPickup  how far are you on upgrading process? I have 2.7 on my machine and there are sooo many warnings.

**Comment by EricPickup** [comment]
@amanpatel123 I'm on 2.7 now too, a whole lot of warnings 😩 
Looks like we have to upgrade all the gems to suppress most of these warnings. I made a commit yesterday with a lot of gem updates and now there's significantly less warnings. I'll try to catch them as we go

**Comment by amanpatel123** [comment]
Awesome! man. Also I am commenting from GitHub mobile app(beta). Brooo this app is smooth. I love it

**Comment by EricPickup** [comment]
> Awesome! man. Also I am commenting from GitHub mobile app(beta). Brooo this app is smooth. I love it

I just got it too. Loving it so far, definitely needed this 😍
