### ISSUE TITLE
Make news postings on home page into individual posts

### ISSUE THREAD

**Issue by EricPickup** [UWindsorCSS/hub#153]
Right now the home page is one big block of markdown text. To add a post we've been adding to that markdown file every time and figuring out the formatting.

Here's what it looks like right now:
![image](https://user-images.githubusercontent.com/1490434/79077069-81bc5f00-7ccc-11ea-9a60-fca12b81fc17.png)

We should make it similar to the events page. You can make an individual post on the home page about some news, e.g.

![image](https://user-images.githubusercontent.com/1490434/79077011-196d7d80-7ccc-11ea-97dd-28bf6ec829f5.png)

And use pagination to see posts from far back.

This could make a good first real task @amanpatel123

**Comment by amanpatel123** [comment]
Ouu! This sounds something fun to do.
