### ISSUE TITLE
Unexpected thing when running `bundle`

### ISSUE THREAD

**Issue by amanpatel123** [UWindsorCSS/hub#154]
Just noticed that when pulling the changes from  master and then running `bundle` it deletes this chunk of lines form Gemfile.lock: 
```  
    omniauth-google-oauth2 (0.8.0)
      jwt (>= 2.0)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (>= 1.6)
```

![image](https://user-images.githubusercontent.com/46072181/79078023-6b65d180-7cd3-11ea-9dae-acc310c6c947.png)

**Comment by amanpatel123** [comment]
@EricPickup I was just wondering why on pulling the changes it did not delete this line `gem 'omniauth-google-oauth2'` from my Gemfile.  Moreover, I see on here that we remove this gem since we replaced it with Microsoft one, but the google OAuth stuff is still in the Gemfile.lock file. 

I just wanted your permission if I can remove this chunk from Gemfile.lock and push it? (I feel that's right to do)

**Comment by EricPickup** [comment]
Feel free to push those changes with it deleted!
