### ISSUE TITLE
Request New/Past events

### ISSUE THREAD

**Issue by amanpatel123** [UWindsorCSS/hub#158]
What if students are given the ability to have more say in what events they want to have? For example
- Students liked the trampoline park event a lot and due to high request, we re-organized it correct?
- May be someone have some event in mind but don't know how to organize it, well CSS have all the resource. Why not give them ability to submit their request. 

If you don't like this idea I can stop working on it! It's not an issue

**Comment by EricPickup** [comment]
Something as simple as a like and dislike system would be cool? Just have students sign in and give them an option to like (and possibly dislike?) events. We can use this system to see what events students like and if we should repeat them.

Not sure how I feel about dislikes - @prairir what do you think?

**Comment by EricPickup** [comment]
As for suggestions for new events, they can just mention it in Discord or email us. Maybe we should add something to the events page that says that
