### ISSUE TITLE
Invalid link to contribute to student guide

### ISSUE THREAD

**Issue by bachittle** [UWindsorCSS/hub#177]
![image](https://user-images.githubusercontent.com/39804642/83175016-4396c580-a0e9-11ea-8775-d47a1ab908b2.png)
![image](https://user-images.githubusercontent.com/39804642/83175047-4f828780-a0e9-11ea-8e1a-233a29d2bf92.png)

#### Expected Behaviour

Clicking on the "Contribute to Guide" link should redirect to 
https://github.com/UWindsorCSS/hub/blob/master/app/views/markdown_pages/GUIDE.markdown

#### Actual Behaviour

Instead it redirects to https://github.com/UWindsorCSS/hub/edit/master/app/views/pages/GUIDE.markdown

**Comment by amanpatel123** [comment]
Oh yeah, I recently changed some files placements and forgot to change this one. Appreciate you help!
