### ISSUE TITLE
Add CSS member/about page

### ISSUE THREAD

**Issue by EricPickup** [UWindsorCSS/hub#82]
Add a page with an introduction to CSS and its members (with photos)

**Comment by HarshdipD** [comment]
I can work on this!

**Comment by EricPickup** [comment]
@HarshdipD if you do, I've since added a About page that this should belong to: https://css.uwindsor.ca/about

**Comment by HarshdipD** [comment]
So what exactly am I doing? Since the page is already there. Just photos?
