### ISSUE TITLE
Send new events and event updates to Discord

### ISSUE THREAD

**Issue by EricPickup** [UWindsorCSS/hub#87]
We'd have to re-add support for the Discord bot but this would be an awesome idea and would keep people engaged in the Discord and CSS website.

**Comment by Scetch** [comment]
Could we just use webhooks to post these into the Discord server and keep the bot separate?

**Comment by EricPickup** [comment]
We might be able to send messages via the bot straight through post requests from the web app. If not then yeah that'd be my preferred way to go

**Comment by EricPickup** [comment]
Sending events on create is deployed in #89, part 2 is sending scheduled reminders
