### ISSUE TITLE
Scroll memory

### ISSUE THREAD

**Issue by HarshdipD** [UWindsorCSS/hub#92]
Possible bug?
When a user goes back to the previous events page, the browser does not remember the scroll position.
### How to reproduce:
1. Go to the events page, scroll to the bottom and click on an event.
2. Go back from that page and you will find that the page has been reset to the top.

Usually, browsers should remember the scrolling position but it's not happening here.

**Comment by shli3** [comment]
I don't know if this has been resolved or looked into, but it works fine on my laptop, it remembered my scrolled position. I'm using Microsoft Edge.

**Comment by EricPickup** [comment]
Working fine for me as well with Chrome
