### ISSUE TITLE
Share button for events

### ISSUE THREAD

**Issue by HarshdipD** [UWindsorCSS/hub#99]

**Comment by amanpatel123** [comment]
So I thought of giving it a try and was actually successful in adding sharing feature but I am facing difficulty changing the size of the buttons

![image](https://user-images.githubusercontent.com/46072181/72401036-f3f6c500-3718-11ea-9823-5f23d5d3b665.png)

@HarshdipD  and @EricPickup would really appreciate if you can give me some idea on how to change some styling of these buttons. I have very less command on styling
